name: docs

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'ayrat555/docs-site'
        submodules: 'recursive'
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - run: |
          git config --global user.email "ayratin555@gmail.com"
          git config --global user.name "Ayrat Badykov"
          git add . && git commit -m "Commit copied files"
    - name: Deploy docs
      run: |
        source ./docs/deploy.sh && build && deploy
